//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yonetimApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProjectManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ProjectManager()
        {
            this.tbl_Project = new HashSet<tbl_Project>();
            this.tbl_TaskforProjectManager = new HashSet<tbl_TaskforProjectManager>();
        }
    
        public int projectManagerId { get; set; }
        public string projectManagerName { get; set; }
        public string projectManagerSurname { get; set; }
        public string projectManagerTeam { get; set; }
        public string projectManagerEmail { get; set; }
        public System.DateTime projectManagerStartDate { get; set; }
        public string projectManagerLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Project> tbl_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TaskforProjectManager> tbl_TaskforProjectManager { get; set; }
    }
}
