//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yonetimApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Manager
    {
        public int managerId { get; set; }
        public string managerName { get; set; }
        public string managerSurname { get; set; }
        public string managerTeam { get; set; }
        public string managerMail { get; set; }
        public System.DateTime managerStartDate { get; set; }
        public string managerLocation { get; set; }
    }
}
