//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yonetimApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Personel()
        {
            this.tbl_TaskforPersonel = new HashSet<tbl_TaskforPersonel>();
            this.tbl_Project = new HashSet<tbl_Project>();
        }
    
        public int personelId { get; set; }
        public string personelName { get; set; }
        public string personelSurname { get; set; }
        public string personelTeam { get; set; }
        public string personelMail { get; set; }
        public System.DateTime personelStartDate { get; set; }
        public string personelLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TaskforPersonel> tbl_TaskforPersonel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Project> tbl_Project { get; set; }
    }
}
